### ISSUE TITLE
Code does not run properly (not up to date ?)

### ISSUE THREAD

**Issue by ugo-fl** [arunoda/meteor-streams-chat-app#1]
Hi mate and thank you for this piece of work.

Here is the error :

W202504-20:44:56.952(7)? (STDERR) /home/ubuntu/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:173
W202504-20:44:56.953(7)? (STDERR)                       throw(ex);
W202504-20:44:56.954(7)? (STDERR)                             ^
W202504-20:44:56.958(7)? (STDERR) TypeError: undefined is not a function
W202504-20:44:56.959(7)? (STDERR)     at app/lib/namespace.js:5:14
W202504-20:44:56.960(7)? (STDERR)     at app/lib/namespace.js:7:3
W202504-20:44:56.960(7)? (STDERR)     at /home/ubuntu/Documents/Worspace/meteor/meteor-streams-chat-app/.meteor/local/build/programs/server/boot.js:154:10
W202504-20:44:56.961(7)? (STDERR)     at Array.forEach (native)
W202504-20:44:56.962(7)? (STDERR)     at Function._.each._.forEach (/home/ubuntu/.meteor/tools/0b2f28e18b/lib/node_modules/underscore/underscore.js:79:11)
W202504-20:44:56.962(7)? (STDERR)     at /home/ubuntu/Documents/Worspace/meteor/meteor-streams-chat-app/.meteor/local/build/programs/server/boot.js:81:5
=> Exited with code: 8

**Comment by arunoda** [comment]
did you run `mrt update` ?

**Comment by ugo-fl** [comment]
Sorry for the bother ! I didn't realize it was using Atmosphere's packages, even if it was obvious ;-)

**Comment by arunoda** [comment]
No Problem :)

On Thu, Dec 5, 2013 at 10:10 AM, Ugo notifications@github.com wrote:

> Sorry for the bother ! I didn't realize it was using Atmosphere's
> packages, even if it was obvious ;-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-streams-chat-app/issues/1#issuecomment-29871136
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
